apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-demo-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /example-proxy
        backend:
          serviceName: demo-proxy-app
          servicePort: 8080