replicaCount: 1

image:
  repository: stefanccaraiman/flask-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: app
  type: NodePort
  externalPort: 80
  internalPort: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
